
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-22T08:30:46-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "daa7a7aa628fd709885ee9b937f0c9a6f6df9cab",
 "version": "2.50.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
