# This file is @generated by templates/torch/_integer.py.jinja.
# Do not edit.
import torch
from jaxtyping import Integer

I = Integer[torch.Tensor, ""]
IN = Integer[torch.Tensor, "N"]
I33 = Integer[torch.Tensor, "3 3"]
I34 = Integer[torch.Tensor, "3 4"]
I43 = Integer[torch.Tensor, "4 3"]
I44 = Integer[torch.Tensor, "4 4"]
IMN = Integer[torch.Tensor, "M N"]
IN3 = Integer[torch.Tensor, "N 3"]
IN4 = Integer[torch.Tensor, "N 4"]
INN = Integer[torch.Tensor, "N N"]
