# Generated by Django 5.1.2 on 2024-10-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_pylabels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="labelspecification",
            name="created",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="labelspecification",
            name="updated",
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
