# minim distance between shapes
MIN_DISTANCE = 2

# Colours
COLOUR_OBJECT = "black"
OPACITY_OBJECT: float = 1
OPACITY_GUIDES: float = 0.5

# iterations
MAX_ITERATIONS = 1000
FIT_SPACING_PRECISION = 0.0001
FIT_FA2TA_RATIO = 0.5

WARNINGS = True

# stimulus pairs
VERT_ECCENTRICITY_STIMPAIR = 350

FILE_ENCODING = "utf-8"

JSON_FLOAT_ROUNDING = 2
