depends = ('ITKPyBase', 'ITKMesh', 'ITKImageSources', 'ITKCommon', )
templates = (  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS2PSSS2', True, 'itk::Image< signed short,2 >, itk::PointSet< signed short,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS2MSS2', True, 'itk::Image< signed short,2 >, itk::Mesh< signed short,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS2PSUC2', True, 'itk::Image< signed short,2 >, itk::PointSet< unsigned char,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS2MUC2', True, 'itk::Image< signed short,2 >, itk::Mesh< unsigned char,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS2PSUS2', True, 'itk::Image< signed short,2 >, itk::PointSet< unsigned short,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS2MUS2', True, 'itk::Image< signed short,2 >, itk::Mesh< unsigned short,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS2PSF2', True, 'itk::Image< signed short,2 >, itk::PointSet< float,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS2MF2', True, 'itk::Image< signed short,2 >, itk::Mesh< float,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS2PSD2', True, 'itk::Image< signed short,2 >, itk::PointSet< double,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS2MD2', True, 'itk::Image< signed short,2 >, itk::Mesh< double,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC2PSSS2', True, 'itk::Image< unsigned char,2 >, itk::PointSet< signed short,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC2MSS2', True, 'itk::Image< unsigned char,2 >, itk::Mesh< signed short,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC2PSUC2', True, 'itk::Image< unsigned char,2 >, itk::PointSet< unsigned char,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC2MUC2', True, 'itk::Image< unsigned char,2 >, itk::Mesh< unsigned char,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC2PSUS2', True, 'itk::Image< unsigned char,2 >, itk::PointSet< unsigned short,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC2MUS2', True, 'itk::Image< unsigned char,2 >, itk::Mesh< unsigned short,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC2PSF2', True, 'itk::Image< unsigned char,2 >, itk::PointSet< float,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC2MF2', True, 'itk::Image< unsigned char,2 >, itk::Mesh< float,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC2PSD2', True, 'itk::Image< unsigned char,2 >, itk::PointSet< double,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC2MD2', True, 'itk::Image< unsigned char,2 >, itk::Mesh< double,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS2PSSS2', True, 'itk::Image< unsigned short,2 >, itk::PointSet< signed short,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS2MSS2', True, 'itk::Image< unsigned short,2 >, itk::Mesh< signed short,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS2PSUC2', True, 'itk::Image< unsigned short,2 >, itk::PointSet< unsigned char,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS2MUC2', True, 'itk::Image< unsigned short,2 >, itk::Mesh< unsigned char,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS2PSUS2', True, 'itk::Image< unsigned short,2 >, itk::PointSet< unsigned short,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS2MUS2', True, 'itk::Image< unsigned short,2 >, itk::Mesh< unsigned short,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS2PSF2', True, 'itk::Image< unsigned short,2 >, itk::PointSet< float,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS2MF2', True, 'itk::Image< unsigned short,2 >, itk::Mesh< float,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS2PSD2', True, 'itk::Image< unsigned short,2 >, itk::PointSet< double,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS2MD2', True, 'itk::Image< unsigned short,2 >, itk::Mesh< double,2 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS3PSSS3', True, 'itk::Image< signed short,3 >, itk::PointSet< signed short,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS3MSS3', True, 'itk::Image< signed short,3 >, itk::Mesh< signed short,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS3PSUC3', True, 'itk::Image< signed short,3 >, itk::PointSet< unsigned char,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS3MUC3', True, 'itk::Image< signed short,3 >, itk::Mesh< unsigned char,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS3PSUS3', True, 'itk::Image< signed short,3 >, itk::PointSet< unsigned short,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS3MUS3', True, 'itk::Image< signed short,3 >, itk::Mesh< unsigned short,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS3PSF3', True, 'itk::Image< signed short,3 >, itk::PointSet< float,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS3MF3', True, 'itk::Image< signed short,3 >, itk::Mesh< float,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS3PSD3', True, 'itk::Image< signed short,3 >, itk::PointSet< double,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS3MD3', True, 'itk::Image< signed short,3 >, itk::Mesh< double,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC3PSSS3', True, 'itk::Image< unsigned char,3 >, itk::PointSet< signed short,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC3MSS3', True, 'itk::Image< unsigned char,3 >, itk::Mesh< signed short,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC3PSUC3', True, 'itk::Image< unsigned char,3 >, itk::PointSet< unsigned char,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC3MUC3', True, 'itk::Image< unsigned char,3 >, itk::Mesh< unsigned char,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC3PSUS3', True, 'itk::Image< unsigned char,3 >, itk::PointSet< unsigned short,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC3MUS3', True, 'itk::Image< unsigned char,3 >, itk::Mesh< unsigned short,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC3PSF3', True, 'itk::Image< unsigned char,3 >, itk::PointSet< float,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC3MF3', True, 'itk::Image< unsigned char,3 >, itk::Mesh< float,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC3PSD3', True, 'itk::Image< unsigned char,3 >, itk::PointSet< double,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC3MD3', True, 'itk::Image< unsigned char,3 >, itk::Mesh< double,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS3PSSS3', True, 'itk::Image< unsigned short,3 >, itk::PointSet< signed short,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS3MSS3', True, 'itk::Image< unsigned short,3 >, itk::Mesh< signed short,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS3PSUC3', True, 'itk::Image< unsigned short,3 >, itk::PointSet< unsigned char,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS3MUC3', True, 'itk::Image< unsigned short,3 >, itk::Mesh< unsigned char,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS3PSUS3', True, 'itk::Image< unsigned short,3 >, itk::PointSet< unsigned short,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS3MUS3', True, 'itk::Image< unsigned short,3 >, itk::Mesh< unsigned short,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS3PSF3', True, 'itk::Image< unsigned short,3 >, itk::PointSet< float,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS3MF3', True, 'itk::Image< unsigned short,3 >, itk::Mesh< float,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS3PSD3', True, 'itk::Image< unsigned short,3 >, itk::PointSet< double,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS3MD3', True, 'itk::Image< unsigned short,3 >, itk::Mesh< double,3 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS4PSSS4', True, 'itk::Image< signed short,4 >, itk::PointSet< signed short,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS4MSS4', True, 'itk::Image< signed short,4 >, itk::Mesh< signed short,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS4PSUC4', True, 'itk::Image< signed short,4 >, itk::PointSet< unsigned char,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS4MUC4', True, 'itk::Image< signed short,4 >, itk::Mesh< unsigned char,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS4PSUS4', True, 'itk::Image< signed short,4 >, itk::PointSet< unsigned short,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS4MUS4', True, 'itk::Image< signed short,4 >, itk::Mesh< unsigned short,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS4PSF4', True, 'itk::Image< signed short,4 >, itk::PointSet< float,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS4MF4', True, 'itk::Image< signed short,4 >, itk::Mesh< float,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS4PSD4', True, 'itk::Image< signed short,4 >, itk::PointSet< double,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterISS4MD4', True, 'itk::Image< signed short,4 >, itk::Mesh< double,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC4PSSS4', True, 'itk::Image< unsigned char,4 >, itk::PointSet< signed short,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC4MSS4', True, 'itk::Image< unsigned char,4 >, itk::Mesh< signed short,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC4PSUC4', True, 'itk::Image< unsigned char,4 >, itk::PointSet< unsigned char,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC4MUC4', True, 'itk::Image< unsigned char,4 >, itk::Mesh< unsigned char,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC4PSUS4', True, 'itk::Image< unsigned char,4 >, itk::PointSet< unsigned short,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC4MUS4', True, 'itk::Image< unsigned char,4 >, itk::Mesh< unsigned short,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC4PSF4', True, 'itk::Image< unsigned char,4 >, itk::PointSet< float,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC4MF4', True, 'itk::Image< unsigned char,4 >, itk::Mesh< float,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC4PSD4', True, 'itk::Image< unsigned char,4 >, itk::PointSet< double,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUC4MD4', True, 'itk::Image< unsigned char,4 >, itk::Mesh< double,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS4PSSS4', True, 'itk::Image< unsigned short,4 >, itk::PointSet< signed short,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS4MSS4', True, 'itk::Image< unsigned short,4 >, itk::Mesh< signed short,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS4PSUC4', True, 'itk::Image< unsigned short,4 >, itk::PointSet< unsigned char,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS4MUC4', True, 'itk::Image< unsigned short,4 >, itk::Mesh< unsigned char,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS4PSUS4', True, 'itk::Image< unsigned short,4 >, itk::PointSet< unsigned short,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS4MUS4', True, 'itk::Image< unsigned short,4 >, itk::Mesh< unsigned short,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS4PSF4', True, 'itk::Image< unsigned short,4 >, itk::PointSet< float,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS4MF4', True, 'itk::Image< unsigned short,4 >, itk::Mesh< float,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS4PSD4', True, 'itk::Image< unsigned short,4 >, itk::PointSet< double,4 >'),
  ('LabelToPointSetFilter', 'itk::LabelToPointSetFilter', 'itkLabelToPointSetFilterIUS4MD4', True, 'itk::Image< unsigned short,4 >, itk::Mesh< double,4 >'),
)
factories = ()
