
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-21T16:31:11-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "eee2caf287ad6e0d6102fde4df512b5a1ad302c9",
 "version": "0.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
