# coding: utf-8

"""
    Tickforge API

    An API to interact with Uptick Internal Resources

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict
from pydantic import BaseModel, Field, StrictStr

class CodeMetricBlobPayload(BaseModel):
    """
    CodeMetricBlobPayload
    """
    name: StrictStr = Field(...)
    data: Dict[str, Any] = Field(...)
    __properties = ["name", "data"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CodeMetricBlobPayload:
        """Create an instance of CodeMetricBlobPayload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CodeMetricBlobPayload:
        """Create an instance of CodeMetricBlobPayload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CodeMetricBlobPayload.parse_obj(obj)

        _obj = CodeMetricBlobPayload.parse_obj({
            "name": obj.get("name"),
            "data": obj.get("data")
        })
        return _obj


