// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>

#include <rev/REVLibError.h>

#include <rev\SparkLowLevel.h>

#include <rpygen/frc__MotorController.hpp>

namespace rpygen {

using namespace rev::spark;

template <typename CfgBase = EmptyTrampolineCfg>
struct PyTrampolineCfg_rev__spark__SparkLowLevel :
  PyTrampolineCfg_frc__MotorController<
  CfgBase
  >
{
  using Base = rev::spark::SparkLowLevel;
};

template <typename PyTrampolineBase, typename PyTrampolineCfg>
using PyTrampolineBase_rev__spark__SparkLowLevel =
  PyTrampoline_frc__MotorController<
    PyTrampolineBase
    , PyTrampolineCfg>
;

template <typename PyTrampolineBase, typename PyTrampolineCfg>
struct PyTrampoline_rev__spark__SparkLowLevel : PyTrampolineBase_rev__spark__SparkLowLevel<PyTrampolineBase, PyTrampolineCfg> {
  using PyTrampolineBase_rev__spark__SparkLowLevel<PyTrampolineBase, PyTrampolineCfg>::PyTrampolineBase_rev__spark__SparkLowLevel;
  using PeriodicStatus0 [[maybe_unused]] = typename rev::spark::SparkLowLevel::PeriodicStatus0;
  using PeriodicStatus1 [[maybe_unused]] = typename rev::spark::SparkLowLevel::PeriodicStatus1;
  using PeriodicStatus2 [[maybe_unused]] = typename rev::spark::SparkLowLevel::PeriodicStatus2;
  using PeriodicStatus3 [[maybe_unused]] = typename rev::spark::SparkLowLevel::PeriodicStatus3;
  using PeriodicStatus4 [[maybe_unused]] = typename rev::spark::SparkLowLevel::PeriodicStatus4;
  using PeriodicStatus5 [[maybe_unused]] = typename rev::spark::SparkLowLevel::PeriodicStatus5;
  using PeriodicStatus6 [[maybe_unused]] = typename rev::spark::SparkLowLevel::PeriodicStatus6;
  using PeriodicStatus7 [[maybe_unused]] = typename rev::spark::SparkLowLevel::PeriodicStatus7;
  using MotorType [[maybe_unused]] = typename rev::spark::SparkLowLevel::MotorType;
  using ControlType [[maybe_unused]] = typename rev::spark::SparkLowLevel::ControlType;
  using ParameterStatus [[maybe_unused]] = typename rev::spark::SparkLowLevel::ParameterStatus;
  using PeriodicFrame [[maybe_unused]] = typename rev::spark::SparkLowLevel::PeriodicFrame;
  using SparkModel [[maybe_unused]] = typename rev::spark::SparkLowLevel::SparkModel;
  using REVLibError = rev::REVLibError;
};

}; // namespace rpygen
