"""
------------------------------------------------------------------------------
<auto-generated>
    This code was auto-generated by main/tools/jsonparser.
    Do not change this file.
</auto-generated>
------------------------------------------------------------------------------
"""
import json
import sys
import re
from six import string_types
from .RequestStatus import RequestStatus
from .AppConfigs import AppConfigs

# Unused import over optimization prevention
str(repr(RequestStatus))
str(repr(AppConfigs))


if sys.version_info > (3,):
    long = int
    unicode = str

class AppConfigsResponse(object):
    """listing of all app configs"""
    def __init__(self, propDict=None):
        fromDict = propDict is not None and isinstance(propDict, dict)
        self.appconfigs = (
            None if not fromDict or propDict.get(
                "appconfigs"
            ) is None
            else [ AppConfigs(i)
            for i in propDict["appconfigs"] ])
        self.requestStatus = (
            None if not fromDict or propDict.get(
                "requestStatus"
            ) is None
            else propDict["requestStatus"])

    @property
    def appconfigs(self):
        """list: array of object that describes app configs"""
        return self._appconfigs

    @appconfigs.setter
    def appconfigs(self, value):
        if value is not None and not isinstance(value, list):
            value = list(value)
        if (value is None) or isinstance(value, list):
            self._appconfigs = value
        else:
            raise TypeError(
                'Property "appconfigs" of type "list<AppConfigs>" set to wron'
                'g type'
            )

    @property
    def requestStatus(self):
        """ """
        return self._requestStatus

    @requestStatus.setter
    def requestStatus(self, value):
        if value is not None and not isinstance(value, RequestStatus):
            value = RequestStatus(value)
        if (value is None) or isinstance(value, RequestStatus):
            self._requestStatus = value
        else:
            raise TypeError(
                'Property "requestStatus" of type "list<RequestStatus>" set t'
                'o wrong type'
            )

    def toDict(self):
        result = {}
        if self._appconfigs:
            result["appconfigs"] = [
                i.toDict() for i in self._appconfigs 
            ] if self._appconfigs else []
        if self._requestStatus:
            result["requestStatus"] = \
                self._requestStatus.toDict() if self._requestStatus is not None else None
        return result

    def toJSON(self, pretty=False):
        if pretty:
            return json.dumps(self.toDict(), sort_keys=True, indent=4)
        else:
            return json.dumps(self.toDict(), sort_keys=True)

    def isValid(self):
        if (self._appconfigs is not None):
            for obj in self._appconfigs:
                if (obj is not None): obj.isValid()
        if (self._requestStatus is not None): self._requestStatus.isValid()
        return True
    

