"""
------------------------------------------------------------------------------
<auto-generated>
    This code was auto-generated by main/tools/jsonparser.
    Do not change this file.
</auto-generated>
------------------------------------------------------------------------------
"""
import json
import sys
import re
from six import string_types

# Unused import over optimization prevention


if sys.version_info > (3,):
    long = int
    unicode = str

class SecurityMinimunSupportedVersion(object):
    def __init__(self, propDict=None):
        fromDict = propDict is not None and isinstance(propDict, dict)
        self.fieldName = (
            None if not fromDict or propDict.get(
                "fieldName"
            ) is None
            else propDict["fieldName"])
        self.minimunSupportedVersion = (
            None if not fromDict or propDict.get(
                "minimunSupportedVersion"
            ) is None
            else propDict["minimunSupportedVersion"])

    @property
    def fieldName(self):
        """ """
        return self._fieldName

    @fieldName.setter
    def fieldName(self, value):
        if value is not None and not isinstance(value, string_types):
            value = repr(value)
        if (value is None) or isinstance(value, string_types):
            self._fieldName = value
        else:
            raise TypeError(
                'Property "fieldName" of type "list<str>" set to wrong type'
            )

    @property
    def minimunSupportedVersion(self):
        """ """
        return self._minimunSupportedVersion

    @minimunSupportedVersion.setter
    def minimunSupportedVersion(self, value):
        if value is not None and not isinstance(value, string_types):
            value = repr(value)
        if (value is None) or isinstance(value, string_types):
            self._minimunSupportedVersion = value
        else:
            raise TypeError(
                'Property "minimunSupportedVersion" of type "list<str>" set t'
                'o wrong type'
            )

    def toDict(self):
        result = {}
        if self._fieldName is not None:
            result["fieldName"] = \
                self._fieldName
        if self._minimunSupportedVersion is not None:
            result["minimunSupportedVersion"] = \
                self._minimunSupportedVersion
        return result

    def toJSON(self, pretty=False):
        if pretty:
            return json.dumps(self.toDict(), sort_keys=True, indent=4)
        else:
            return json.dumps(self.toDict(), sort_keys=True)

    def isValid(self):
        return True
    

