# coding: utf-8

# flake8: noqa

"""
    smallmodelsapi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.3.1"

# import apis into sdk package
from smallmodels.api.ggrfhvac_update_api import GGRFHVACUpdateApi
from smallmodels.api.health_data_api import HealthDataApi
from smallmodels.api.range_upgrade_api import RangeUpgradeApi

# import ApiClient
from smallmodels.api_response import ApiResponse
from smallmodels.api_client import ApiClient
from smallmodels.configuration import Configuration
from smallmodels.exceptions import OpenApiException
from smallmodels.exceptions import ApiTypeError
from smallmodels.exceptions import ApiValueError
from smallmodels.exceptions import ApiKeyError
from smallmodels.exceptions import ApiAttributeError
from smallmodels.exceptions import ApiException

# import models into sdk package
from smallmodels.models.energy_quantity import EnergyQuantity
from smallmodels.models.energy_tradeoff import EnergyTradeoff
from smallmodels.models.group_by import GroupBy
from smallmodels.models.http_validation_error import HTTPValidationError
from smallmodels.models.hvac_efficiency_electric_detailed import HvacEfficiencyElectricDetailed
from smallmodels.models.hvac_efficiency_fossil_fuels import HvacEfficiencyFossilFuels
from smallmodels.models.hvac_update_results import HvacUpdateResults
from smallmodels.models.metrics import Metrics
from smallmodels.models.range_fuel_type import RangeFuelType
from smallmodels.models.upgrade_option import UpgradeOption
from smallmodels.models.validation_error import ValidationError
from smallmodels.models.validation_error_loc_inner import ValidationErrorLocInner
