// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>

#include <rev/config/LimitSwitchConfig.h>

#include <rpygen/rev__spark__BaseConfig.hpp>

namespace rpygen {

using namespace rev::spark;

template <typename CfgBase = EmptyTrampolineCfg>
struct PyTrampolineCfg_rev__spark__LimitSwitchConfig :
  PyTrampolineCfg_rev__spark__BaseConfig<
  CfgBase
  >
{
  using Base = rev::spark::LimitSwitchConfig;
};

template <typename PyTrampolineBase, typename PyTrampolineCfg>
using PyTrampolineBase_rev__spark__LimitSwitchConfig =
  PyTrampoline_rev__spark__BaseConfig<
    PyTrampolineBase
    , PyTrampolineCfg>
;

template <typename PyTrampolineBase, typename PyTrampolineCfg>
struct PyTrampoline_rev__spark__LimitSwitchConfig : PyTrampolineBase_rev__spark__LimitSwitchConfig<PyTrampolineBase, PyTrampolineCfg> {
  using PyTrampolineBase_rev__spark__LimitSwitchConfig<PyTrampolineBase, PyTrampolineCfg>::PyTrampolineBase_rev__spark__LimitSwitchConfig;
  using Type [[maybe_unused]] = typename rev::spark::LimitSwitchConfig::Type;
};

}; // namespace rpygen
