DEFAULT_SETTINGS = {
    "PYTHON_VERSION": "3.10",
    "NUMPY_VERSION": "1.26",
    "TENSORFLOW_VERSION": "2.17",
    "PYTORCH_VERSION": "2.5",
    "KERAS_VERSION": "3.6",
    "CUDA_VERSION": "11.8"
}