# This file is @generated by templates/torch/_float.py.jinja.
# Do not edit.
import torch
from jaxtyping import Float

F = Float[torch.Tensor, ""]
FN = Float[torch.Tensor, "N"]
F33 = Float[torch.Tensor, "3 3"]
F34 = Float[torch.Tensor, "3 4"]
F43 = Float[torch.Tensor, "4 3"]
F44 = Float[torch.Tensor, "4 4"]
FMN = Float[torch.Tensor, "M N"]
FN3 = Float[torch.Tensor, "N 3"]
FN4 = Float[torch.Tensor, "N 4"]
FNN = Float[torch.Tensor, "N N"]
