"""
Predefined mapping for which column should go in which table.

CATEGORY_MAP: Dict[column, table]
"""


CATEGORY_MAP = {
    "Aer A/90": "Stats",
    "Hdrs W/90": "Stats",
    "Blk/90": "Stats",
    "Clr/90": "Stats",
    "Tck/90": "Stats",
    "Pres A/90": "Stats",
    "Pres C/90": "Stats",
    "Int/90": "Stats",
    "Sprints/90": "Stats",
    "Poss Lost/90": "Stats",
    "Poss Won/90": "Stats",
    "Drb/90": "Stats",
    "OP-Crs A/90": "Stats",
    "OP-Crs C/90": "Stats",
    "Ps A/90": "Stats",
    "Ps C/90": "Stats",
    "Pr passes/90": "Stats",
    "OP-KP/90": "Stats",
    "Ch C/90": "Stats",
    "xA/90": "Stats",
    "Shot/90": "Stats",
    "ShT/90": "Stats",
    "NP-xG/90": "Stats",

    "Cor": "Attributes",
    "Cro": "Attributes",
    "Dri": "Attributes",
    "Fin": "Attributes",
    "Fir": "Attributes",
    "Fre": "Attributes",
    "Hea": "Attributes",
    "Lon": "Attributes",
    "L Th": "Attributes",
    "Mar": "Attributes",
    "Pas": "Attributes",
    "Pen": "Attributes",
    "Tck": "Attributes",
    "Tec": "Attributes",
    "Agg": "Attributes",
    "Ant": "Attributes",
    "Bra": "Attributes",
    "Cmp": "Attributes",
    "Cnt": "Attributes",
    "Dec": "Attributes",
    "Det": "Attributes",
    "Fla": "Attributes",
    "Ldr": "Attributes",
    "OtB": "Attributes",
    "Pos": "Attributes",
    "Tea": "Attributes",
    "Vis": "Attributes",
    "Wor": "Attributes",
    "Acc": "Attributes",
    "Agi": "Attributes",
    "Bal": "Attributes",
    "Jum": "Attributes",
    "NatF": "Attributes",
    "Pac": "Attributes",
    "Sta": "Attributes",
    "Str": "Attributes",
    "Aer": "Attributes",
    "Cmd": "Attributes",
    "Com": "Attributes",
    "Ecc": "Attributes",
    "Han": "Attributes",
    "Kic": "Attributes",
    "1v1": "Attributes",
    "Pun": "Attributes",
    "Ref": "Attributes",
    "TRO": "Attributes",
    "Thr": "Attributes",

    "Begins": "Contract",
    "Expires": "Contract",
    "Opt Ext by Club": "Contract",
    "Wage": "Contract",
    "AP": "Contract",
    "Min Fee Rls": "Contract",

    "Name": "Player",
    "UID": "Player",

    "Age": "PlayerInfo",
    "Position": "PlayerInfo",
    "Right Foot": "PlayerInfo",
    "Left Foot": "PlayerInfo",
    "Mins": "PlayerInfo",
    "Division": "PlayerInfo",
    "Club": "PlayerInfo",
    "Nat": "PlayerInfo",
    "Eligible": "PlayerInfo",

    "CA": "Ca",

    "Team": "Unused",
    "Caps": "Unused",
    "Yth Apps": "Unused",
    "Inf": "Unused",
    "Rec": "Unused"
}
