# This file automatically generated by
#    /home/couchbase/jenkins/workspace/python/sdk/python-scripted-build-pipeline/py-client/couchbase_version.py
# at
#    2024-11-25 20:51:10.647237
__version__ = '4.3.4'