# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ambient_backend_api_client.models.request import Request

class TestRequest(unittest.TestCase):
    """Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Request:
        """Test Request
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Request`
        """
        model = Request()
        if include_optional:
            return Request(
                name = '',
                resource_type = 'cluster',
                identifier = '',
                owner_id = '',
                owner_type = 'individual',
                description = '',
                requests = [
                    ''
                    ],
                notifications = [
                    ''
                    ],
                status = 'pending',
                error = '',
                requested_ts = 1.337,
                started_ts = 1.337,
                failed_ts = 1.337,
                completed_ts = 1.337,
                notes = [
                    ''
                    ],
                data = ambient_backend_api_client.models.data.Data()
            )
        else:
            return Request(
                name = '',
                identifier = '',
                owner_id = '',
                owner_type = 'individual',
        )
        """

    def testRequest(self):
        """Test Request"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
