# Generated by Django 5.1.3 on 2024-11-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_variable", "0002_alter_configuration_options_configuration_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="value",
            field=models.TextField(blank=True, null=True),
        ),
    ]
