
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-20T19:37:35-0600",
 "dirty": true,
 "error": null,
 "full-revisionid": "78ee41cb26058cc2dfba8aece6a2471ec5ea3675",
 "version": "3.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
