# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hri_msgs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import shared_msgs_pb2 as shared__msgs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ehri_msgs.proto\x12\x1aIndyFramework.Protobuf.HRI\x1a\x11shared_msgs.proto\"\x14\n\x12GetRefFrameListReq\"\x82\x01\n\x12GetRefFrameListRes\x12I\n\nref_frames\x18\x01 \x03(\x0b\x32\x35.IndyFramework.Protobuf.Shared.NamedReferencePosition\x12\x14\n\x0c\x64\x65\x66\x61ult_name\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x64 \x01(\t\"u\n\x12SetRefFrameListReq\x12I\n\nref_frames\x18\x01 \x03(\x0b\x32\x35.IndyFramework.Protobuf.Shared.NamedReferencePosition\x12\x14\n\x0c\x64\x65\x66\x61ult_name\x18\x02 \x01(\t\"!\n\x12SetRefFrameListRes\x12\x0b\n\x03msg\x18\x64 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hri_msgs_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETREFFRAMELISTREQ']._serialized_start=65
  _globals['_GETREFFRAMELISTREQ']._serialized_end=85
  _globals['_GETREFFRAMELISTRES']._serialized_start=88
  _globals['_GETREFFRAMELISTRES']._serialized_end=218
  _globals['_SETREFFRAMELISTREQ']._serialized_start=220
  _globals['_SETREFFRAMELISTREQ']._serialized_end=337
  _globals['_SETREFFRAMELISTRES']._serialized_start=339
  _globals['_SETREFFRAMELISTRES']._serialized_end=372
# @@protoc_insertion_point(module_scope)
