# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ambient_backend_api_client.models.request_status_enum import RequestStatusEnum

class TestRequestStatusEnum(unittest.TestCase):
    """RequestStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestStatusEnum(self):
        """Test RequestStatusEnum"""
        # inst = RequestStatusEnum()

if __name__ == '__main__':
    unittest.main()
