# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ambient_backend_api_client.api.notifications_api import NotificationsApi


class TestNotificationsApi(unittest.TestCase):
    """NotificationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotificationsApi()

    def tearDown(self) -> None:
        pass

    def test_create_notification_notifications_post(self) -> None:
        """Test case for create_notification_notifications_post

        Create Notification
        """
        pass

    def test_delete_notification_notifications_notification_id_delete(self) -> None:
        """Test case for delete_notification_notifications_notification_id_delete

        Delete Notification
        """
        pass

    def test_get_notification_notifications_notification_id_get(self) -> None:
        """Test case for get_notification_notifications_notification_id_get

        Get Notification
        """
        pass

    def test_get_notifications_notifications_get(self) -> None:
        """Test case for get_notifications_notifications_get

        Get Notifications
        """
        pass

    def test_patch_notification_notifications_notification_id_patch(self) -> None:
        """Test case for patch_notification_notifications_notification_id_patch

        Patch Notification
        """
        pass


if __name__ == '__main__':
    unittest.main()
