# coding: utf-8

"""
    Antimatter Public API

    Interact with the Antimatter Cloud API

    The version of the OpenAPI document: 2.0.13
    Contact: support@antimatter.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from antimatter_api.models.domain_identity_principal_details import DomainIdentityPrincipalDetails

class TestDomainIdentityPrincipalDetails(unittest.TestCase):
    """DomainIdentityPrincipalDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DomainIdentityPrincipalDetails:
        """Test DomainIdentityPrincipalDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DomainIdentityPrincipalDetails`
        """
        model = DomainIdentityPrincipalDetails()
        if include_optional:
            return DomainIdentityPrincipalDetails(
                type = 'APIKey',
                api_key_id = '',
                comment = '',
                email = '',
                hosted_domain = '',
                tenant_id = ''
            )
        else:
            return DomainIdentityPrincipalDetails(
                email = '',
                hosted_domain = '',
                tenant_id = '',
        )
        """

    def testDomainIdentityPrincipalDetails(self):
        """Test DomainIdentityPrincipalDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
