# coding: utf-8

"""
    Antimatter Public API

    Interact with the Antimatter Cloud API

    The version of the OpenAPI document: 2.0.13
    Contact: support@antimatter.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from antimatter_api.models.new_data_policy import NewDataPolicy

class TestNewDataPolicy(unittest.TestCase):
    """NewDataPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NewDataPolicy:
        """Test NewDataPolicy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NewDataPolicy`
        """
        model = NewDataPolicy()
        if include_optional:
            return NewDataPolicy(
                description = '',
                name = '/B98JLe5iL60 aa -Ctq9dcsc-2 790gAa7Xa5u50ArrlGpCQjkQVRmfnjddwcDM-9fvlxVU94mAsDwtJsoLm/U1QzcAPbMGoFtYYnOi2Uynm6 iBPXDeXK6FerdNFRGYVtmAOl4_Cq1Rl3hC1QiYJ4AOF66DBqQaK8/sLp3g3V8O 5oXadaJrr2kIA7m74_YUSTN PJy7dgSQzlarQkEaQ6M'
            )
        else:
            return NewDataPolicy(
                description = '',
                name = '/B98JLe5iL60 aa -Ctq9dcsc-2 790gAa7Xa5u50ArrlGpCQjkQVRmfnjddwcDM-9fvlxVU94mAsDwtJsoLm/U1QzcAPbMGoFtYYnOi2Uynm6 iBPXDeXK6FerdNFRGYVtmAOl4_Cq1Rl3hC1QiYJ4AOF66DBqQaK8/sLp3g3V8O 5oXadaJrr2kIA7m74_YUSTN PJy7dgSQzlarQkEaQ6M',
        )
        """

    def testNewDataPolicy(self):
        """Test NewDataPolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
