# coding: utf-8

"""
    Antimatter Public API

    Interact with the Antimatter Cloud API

    The version of the OpenAPI document: 2.0.13
    Contact: support@antimatter.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from antimatter_api.models.capsule_open_response import CapsuleOpenResponse

class TestCapsuleOpenResponse(unittest.TestCase):
    """CapsuleOpenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CapsuleOpenResponse:
        """Test CapsuleOpenResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CapsuleOpenResponse`
        """
        model = CapsuleOpenResponse()
        if include_optional:
            return CapsuleOpenResponse(
                decryption_key = 'YQ==',
                read_context_configuration = antimatter_api.models.capsule_open_response_read_context_configuration.CapsuleOpenResponse_readContextConfiguration(
                    disable_read_logging = True, 
                    key_cache_ttl = 0, 
                    policy_assembly = 'YQ==', ),
                open_token = '0123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263',
                capsule_tags = [
                    antimatter_api.models.tag.Tag(
                        name = 'tag.antimatter.io/pii/name', 
                        value = '', 
                        type = 'string', 
                        source = '', 
                        hook_version = '4.072888001528021798096225500850762068629.39333975650685139102691291732729478601482026', )
                    ]
            )
        else:
            return CapsuleOpenResponse(
                decryption_key = 'YQ==',
                read_context_configuration = antimatter_api.models.capsule_open_response_read_context_configuration.CapsuleOpenResponse_readContextConfiguration(
                    disable_read_logging = True, 
                    key_cache_ttl = 0, 
                    policy_assembly = 'YQ==', ),
                open_token = '0123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263',
                capsule_tags = [
                    antimatter_api.models.tag.Tag(
                        name = 'tag.antimatter.io/pii/name', 
                        value = '', 
                        type = 'string', 
                        source = '', 
                        hook_version = '4.072888001528021798096225500850762068629.39333975650685139102691291732729478601482026', )
                    ],
        )
        """

    def testCapsuleOpenResponse(self):
        """Test CapsuleOpenResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
