# coding: utf-8

"""
    Antimatter Public API

    Interact with the Antimatter Cloud API

    The version of the OpenAPI document: 2.0.13
    Contact: support@antimatter.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from antimatter_api.models.read_parameter_expression import ReadParameterExpression

class TestReadParameterExpression(unittest.TestCase):
    """ReadParameterExpression unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReadParameterExpression:
        """Test ReadParameterExpression
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReadParameterExpression`
        """
        model = ReadParameterExpression()
        if include_optional:
            return ReadParameterExpression(
                name = '',
                values = [
                    ''
                    ],
                operator = 'In',
                variables = [
                    antimatter_api.models.variable_definition.VariableDefinition(
                        variable_name = 'MqX', 
                        source = 'TagValue', 
                        tag_name = '', 
                        capability_name = '', 
                        read_parameter_name = '', 
                        fact_type = 'ic3::ss7djuy2zme', 
                        fact_arguments = [
                            antimatter_api.models.variable_definition_fact_arguments_inner.VariableDefinition_factArguments_inner(
                                operator = 'In', 
                                values = [
                                    ''
                                    ], )
                            ], 
                        variables = [
                            antimatter_api.models.variable_definition.VariableDefinition(
                                variable_name = 'MqX', 
                                source = 'TagValue', 
                                tag_name = '', 
                                capability_name = '', 
                                read_parameter_name = '', )
                            ], )
                    ]
            )
        else:
            return ReadParameterExpression(
                name = '',
                operator = 'In',
        )
        """

    def testReadParameterExpression(self):
        """Test ReadParameterExpression"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
