# coding: utf-8

"""
    Antimatter Public API

    Interact with the Antimatter Cloud API

    The version of the OpenAPI document: 2.0.13
    Contact: support@antimatter.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from antimatter_api.models.data_tagging_hook_response import DataTaggingHookResponse

class TestDataTaggingHookResponse(unittest.TestCase):
    """DataTaggingHookResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataTaggingHookResponse:
        """Test DataTaggingHookResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataTaggingHookResponse`
        """
        model = DataTaggingHookResponse()
        if include_optional:
            return DataTaggingHookResponse(
                version = '3.4.3',
                records = [
                    antimatter_api.models.data_tagging_hook_response_records_inner.DataTaggingHookResponse_records_inner(
                        elements = [
                            antimatter_api.models.tag_set.TagSet(
                                capsule_tags = [
                                    antimatter_api.models.tag.Tag(
                                        name = 'tag.antimatter.io/pii/name', 
                                        value = '', 
                                        type = 'string', 
                                        source = '', 
                                        hook_version = '4.072888001528021798096225500850762068629.39333975650685139102691291732729478601482026', )
                                    ], 
                                span_tags = [
                                    antimatter_api.models.tag_set_span_tags_inner.TagSet_spanTags_inner(
                                        start = 56, 
                                        end = 56, 
                                        tags = [
                                            antimatter_api.models.tag.Tag(
                                                name = 'tag.antimatter.io/pii/name', 
                                                value = '', 
                                                type = 'string', 
                                                source = '', 
                                                hook_version = '4.072888001528021798096225500850762068629.39333975650685139102691291732729478601482026', )
                                            ], )
                                    ], )
                            ], )
                    ]
            )
        else:
            return DataTaggingHookResponse(
                version = '3.4.3',
                records = [
                    antimatter_api.models.data_tagging_hook_response_records_inner.DataTaggingHookResponse_records_inner(
                        elements = [
                            antimatter_api.models.tag_set.TagSet(
                                capsule_tags = [
                                    antimatter_api.models.tag.Tag(
                                        name = 'tag.antimatter.io/pii/name', 
                                        value = '', 
                                        type = 'string', 
                                        source = '', 
                                        hook_version = '4.072888001528021798096225500850762068629.39333975650685139102691291732729478601482026', )
                                    ], 
                                span_tags = [
                                    antimatter_api.models.tag_set_span_tags_inner.TagSet_spanTags_inner(
                                        start = 56, 
                                        end = 56, 
                                        tags = [
                                            antimatter_api.models.tag.Tag(
                                                name = 'tag.antimatter.io/pii/name', 
                                                value = '', 
                                                type = 'string', 
                                                source = '', 
                                                hook_version = '4.072888001528021798096225500850762068629.39333975650685139102691291732729478601482026', )
                                            ], )
                                    ], )
                            ], )
                    ],
        )
        """

    def testDataTaggingHookResponse(self):
        """Test DataTaggingHookResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
