# coding: utf-8

"""
    Antimatter Public API

    Interact with the Antimatter Cloud API

    The version of the OpenAPI document: 2.0.13
    Contact: support@antimatter.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from antimatter_api.models.policy_rule_operation import PolicyRuleOperation

class TestPolicyRuleOperation(unittest.TestCase):
    """PolicyRuleOperation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPolicyRuleOperation(self):
        """Test PolicyRuleOperation"""
        # inst = PolicyRuleOperation()

if __name__ == '__main__':
    unittest.main()
