# coding: utf-8

"""
    Antimatter Public API

    Interact with the Antimatter Cloud API

    The version of the OpenAPI document: 2.0.13
    Contact: support@antimatter.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from antimatter_api.api.policy_api import PolicyApi


class TestPolicyApi(unittest.TestCase):
    """PolicyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PolicyApi()

    def tearDown(self) -> None:
        pass

    def test_domain_create_data_policy(self) -> None:
        """Test case for domain_create_data_policy

        Create a new data policy
        """
        pass

    def test_domain_create_policy_rule(self) -> None:
        """Test case for domain_create_policy_rule

        Create a domain policy rule
        """
        pass

    def test_domain_data_policy_configure_rules(self) -> None:
        """Test case for domain_data_policy_configure_rules

        Configure data policy rules
        """
        pass

    def test_domain_data_policy_rule_update(self) -> None:
        """Test case for domain_data_policy_rule_update

        Configure data policy rule
        """
        pass

    def test_domain_delete_data_policy(self) -> None:
        """Test case for domain_delete_data_policy

        Delete a data policy
        """
        pass

    def test_domain_delete_data_policy_rule(self) -> None:
        """Test case for domain_delete_data_policy_rule

        Delete a data policy policy
        """
        pass

    def test_domain_delete_fact_by_id(self) -> None:
        """Test case for domain_delete_fact_by_id

        Delete a fact
        """
        pass

    def test_domain_delete_fact_by_tuple(self) -> None:
        """Test case for domain_delete_fact_by_tuple

        Delete a fact
        """
        pass

    def test_domain_delete_fact_type(self) -> None:
        """Test case for domain_delete_fact_type

        Delete a fact type
        """
        pass

    def test_domain_delete_policy_rule(self) -> None:
        """Test case for domain_delete_policy_rule

        Delete a domain policy rule
        """
        pass

    def test_domain_get_data_policy(self) -> None:
        """Test case for domain_get_data_policy

        Get a data policy
        """
        pass

    def test_domain_get_data_policy_binding(self) -> None:
        """Test case for domain_get_data_policy_binding

        Retrieve a data policy binding
        """
        pass

    def test_domain_get_data_policy_rule(self) -> None:
        """Test case for domain_get_data_policy_rule

        Get a data policy rule
        """
        pass

    def test_domain_get_fact_by_id(self) -> None:
        """Test case for domain_get_fact_by_id

        Get a fact by ID
        """
        pass

    def test_domain_get_fact_type(self) -> None:
        """Test case for domain_get_fact_type

        Get a fact type definition
        """
        pass

    def test_domain_list_data_policies(self) -> None:
        """Test case for domain_list_data_policies

        """
        pass

    def test_domain_list_fact_types(self) -> None:
        """Test case for domain_list_fact_types

        List the domain's fact types
        """
        pass

    def test_domain_list_facts(self) -> None:
        """Test case for domain_list_facts

        Get facts for a type
        """
        pass

    def test_domain_list_policy_rules(self) -> None:
        """Test case for domain_list_policy_rules

        Get the domain policy rules
        """
        pass

    def test_domain_list_resources(self) -> None:
        """Test case for domain_list_resources

        Get a summary of access control resource paths
        """
        pass

    def test_domain_policy_flush(self) -> None:
        """Test case for domain_policy_flush

        Flush the policy cache
        """
        pass

    def test_domain_put_fact_type(self) -> None:
        """Test case for domain_put_fact_type

        Create a fact type
        """
        pass

    def test_domain_renumber_data_policy_rules(self) -> None:
        """Test case for domain_renumber_data_policy_rules

        Re-assign rule numbers
        """
        pass

    def test_domain_renumber_policy_rules(self) -> None:
        """Test case for domain_renumber_policy_rules

        Re-assign rule numbers
        """
        pass

    def test_domain_set_data_policy_binding(self) -> None:
        """Test case for domain_set_data_policy_binding

        Configure data policy binding
        """
        pass

    def test_domain_update_data_policy(self) -> None:
        """Test case for domain_update_data_policy

        Update a data policy
        """
        pass

    def test_domain_update_policy_rule(self) -> None:
        """Test case for domain_update_policy_rule

        Update a domain policy rule
        """
        pass

    def test_domain_upsert_fact(self) -> None:
        """Test case for domain_upsert_fact

        Upsert a fact
        """
        pass


if __name__ == '__main__':
    unittest.main()
