# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hri_msgs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import shared_msgs_pb2 as shared__msgs__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hri_msgs.proto',
  package='IndyFramework.Protobuf.HRI',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0ehri_msgs.proto\x12\x1aIndyFramework.Protobuf.HRI\x1a\x11shared_msgs.proto\"\x14\n\x12GetRefFrameListReq\"\x82\x01\n\x12GetRefFrameListRes\x12I\n\nref_frames\x18\x01 \x03(\x0b\x32\x35.IndyFramework.Protobuf.Shared.NamedReferencePosition\x12\x14\n\x0c\x64\x65\x66\x61ult_name\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x64 \x01(\t\"u\n\x12SetRefFrameListReq\x12I\n\nref_frames\x18\x01 \x03(\x0b\x32\x35.IndyFramework.Protobuf.Shared.NamedReferencePosition\x12\x14\n\x0c\x64\x65\x66\x61ult_name\x18\x02 \x01(\t\"!\n\x12SetRefFrameListRes\x12\x0b\n\x03msg\x18\x64 \x01(\tb\x06proto3'
  ,
  dependencies=[shared__msgs__pb2.DESCRIPTOR,])




_GETREFFRAMELISTREQ = _descriptor.Descriptor(
  name='GetRefFrameListReq',
  full_name='IndyFramework.Protobuf.HRI.GetRefFrameListReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=85,
)


_GETREFFRAMELISTRES = _descriptor.Descriptor(
  name='GetRefFrameListRes',
  full_name='IndyFramework.Protobuf.HRI.GetRefFrameListRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ref_frames', full_name='IndyFramework.Protobuf.HRI.GetRefFrameListRes.ref_frames', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='default_name', full_name='IndyFramework.Protobuf.HRI.GetRefFrameListRes.default_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='IndyFramework.Protobuf.HRI.GetRefFrameListRes.msg', index=2,
      number=100, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=218,
)


_SETREFFRAMELISTREQ = _descriptor.Descriptor(
  name='SetRefFrameListReq',
  full_name='IndyFramework.Protobuf.HRI.SetRefFrameListReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ref_frames', full_name='IndyFramework.Protobuf.HRI.SetRefFrameListReq.ref_frames', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='default_name', full_name='IndyFramework.Protobuf.HRI.SetRefFrameListReq.default_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=337,
)


_SETREFFRAMELISTRES = _descriptor.Descriptor(
  name='SetRefFrameListRes',
  full_name='IndyFramework.Protobuf.HRI.SetRefFrameListRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='IndyFramework.Protobuf.HRI.SetRefFrameListRes.msg', index=0,
      number=100, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=372,
)

_GETREFFRAMELISTRES.fields_by_name['ref_frames'].message_type = shared__msgs__pb2._NAMEDREFERENCEPOSITION
_SETREFFRAMELISTREQ.fields_by_name['ref_frames'].message_type = shared__msgs__pb2._NAMEDREFERENCEPOSITION
DESCRIPTOR.message_types_by_name['GetRefFrameListReq'] = _GETREFFRAMELISTREQ
DESCRIPTOR.message_types_by_name['GetRefFrameListRes'] = _GETREFFRAMELISTRES
DESCRIPTOR.message_types_by_name['SetRefFrameListReq'] = _SETREFFRAMELISTREQ
DESCRIPTOR.message_types_by_name['SetRefFrameListRes'] = _SETREFFRAMELISTRES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetRefFrameListReq = _reflection.GeneratedProtocolMessageType('GetRefFrameListReq', (_message.Message,), {
  'DESCRIPTOR' : _GETREFFRAMELISTREQ,
  '__module__' : 'hri_msgs_pb2'
  # @@protoc_insertion_point(class_scope:IndyFramework.Protobuf.HRI.GetRefFrameListReq)
  })
_sym_db.RegisterMessage(GetRefFrameListReq)

GetRefFrameListRes = _reflection.GeneratedProtocolMessageType('GetRefFrameListRes', (_message.Message,), {
  'DESCRIPTOR' : _GETREFFRAMELISTRES,
  '__module__' : 'hri_msgs_pb2'
  # @@protoc_insertion_point(class_scope:IndyFramework.Protobuf.HRI.GetRefFrameListRes)
  })
_sym_db.RegisterMessage(GetRefFrameListRes)

SetRefFrameListReq = _reflection.GeneratedProtocolMessageType('SetRefFrameListReq', (_message.Message,), {
  'DESCRIPTOR' : _SETREFFRAMELISTREQ,
  '__module__' : 'hri_msgs_pb2'
  # @@protoc_insertion_point(class_scope:IndyFramework.Protobuf.HRI.SetRefFrameListReq)
  })
_sym_db.RegisterMessage(SetRefFrameListReq)

SetRefFrameListRes = _reflection.GeneratedProtocolMessageType('SetRefFrameListRes', (_message.Message,), {
  'DESCRIPTOR' : _SETREFFRAMELISTRES,
  '__module__' : 'hri_msgs_pb2'
  # @@protoc_insertion_point(class_scope:IndyFramework.Protobuf.HRI.SetRefFrameListRes)
  })
_sym_db.RegisterMessage(SetRefFrameListRes)


# @@protoc_insertion_point(module_scope)
