from .solo import DarkCodz
from .solo import WormGpt
from .solo import ChatGpt
from .solo import Whois
from .solo import IP
from .solo import portscan
from .solo import Marshel
from .solo import MD5
from .solo import SHA1
from .solo import SHA256
from .solo import service_port
from .solo import Base64_Decode
from .solo import Base64_Encode
from .solo import BlackBox
from .solo import ProG_lan
from .solo import Dev