# This file is @generated by templates/jax/_integer.py.jinja.
# Do not edit.
import jax
from jaxtyping import Integer

I = Integer[jax.Array, ""]
IN = Integer[jax.Array, "N"]
I33 = Integer[jax.Array, "3 3"]
I34 = Integer[jax.Array, "3 4"]
I43 = Integer[jax.Array, "4 3"]
I44 = Integer[jax.Array, "4 4"]
IMN = Integer[jax.Array, "M N"]
IN3 = Integer[jax.Array, "N 3"]
IN4 = Integer[jax.Array, "N 4"]
INN = Integer[jax.Array, "N N"]
