# Generated by Django 4.2.7 on 2023-12-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "intecomm_rando",
            "0004_alter_historicalrandomizationlist_device_created_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="randomizationlist",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "permissions": (("display_assignment", "Can display assignment"),),
            },
        ),
        migrations.AlterModelOptions(
            name="registeredgroup",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "ordering": ["group_identifier"],
                "verbose_name": "Registered Group",
                "verbose_name_plural": "Registered Groups",
            },
        ),
        migrations.AlterUniqueTogether(
            name="randomizationlist",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="historicalrandomizationlist",
            name="locale_created",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale created",
            ),
        ),
        migrations.AddField(
            model_name="historicalrandomizationlist",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AddField(
            model_name="historicalregisteredgroup",
            name="locale_created",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale created",
            ),
        ),
        migrations.AddField(
            model_name="historicalregisteredgroup",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AddField(
            model_name="randomizationlist",
            name="locale_created",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale created",
            ),
        ),
        migrations.AddField(
            model_name="randomizationlist",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AddField(
            model_name="registeredgroup",
            name="locale_created",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale created",
            ),
        ),
        migrations.AddField(
            model_name="registeredgroup",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                null=True,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AddIndex(
            model_name="randomizationlist",
            index=models.Index(
                fields=["modified", "created"], name="intecomm_ra_modifie_ece6f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="randomizationlist",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="intecomm_ra_user_mo_09c113_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="registeredgroup",
            index=models.Index(
                fields=["modified", "created"], name="intecomm_ra_modifie_d95d5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registeredgroup",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="intecomm_ra_user_mo_ad3cfe_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="randomizationlist",
            constraint=models.UniqueConstraint(
                fields=("site_name", "sid"),
                name="intecomm_rando_randomizationlist_site_sid_uniq",
            ),
        ),
    ]
