from .core import one
from .core import two
from .core import three
from .core import four
from .core import five
from .core import six
from .core import seven
from .core import eight
from .core import nine
from .core import ten
