#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['versioning']

package_data = \
{'': ['*']}

setup(name='interface-versioning',
      version='1.0.0.0',
      description='Interface Versioning',
      author=None,
      author_email='"Charles C. D. Tolley" <charlescdtolley@protonmail.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      python_requires='>=3.6',
     )
