// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>

#include <rev\SparkFlex.h>

#include <rev/SparkLowLevel.h>

#include <rpygen/rev__spark__SparkBase.hpp>

namespace rpygen {

using namespace rev::spark;

template <typename CfgBase = EmptyTrampolineCfg>
struct PyTrampolineCfg_rev__spark__SparkFlex :
  PyTrampolineCfg_rev__spark__SparkBase<
  CfgBase
  >
{
  using Base = rev::spark::SparkFlex;
};

template <typename PyTrampolineBase, typename PyTrampolineCfg>
using PyTrampolineBase_rev__spark__SparkFlex =
  PyTrampoline_rev__spark__SparkBase<
    PyTrampolineBase
    , PyTrampolineCfg>
;

template <typename PyTrampolineBase, typename PyTrampolineCfg>
struct PyTrampoline_rev__spark__SparkFlex : PyTrampolineBase_rev__spark__SparkFlex<PyTrampolineBase, PyTrampolineCfg> {
  using PyTrampolineBase_rev__spark__SparkFlex<PyTrampolineBase, PyTrampolineCfg>::PyTrampolineBase_rev__spark__SparkFlex;
  using MotorType = rev::spark::SparkLowLevel::MotorType;
};

}; // namespace rpygen
