
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-25T12:22:58-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e996e70fcaa4a4ff94c51e0800edd2e145342c0",
 "version": "1.16.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
