"""
------------------------------------------------------------------------------
<auto-generated>
    This code was auto-generated by main/tools/jsonparser.
    Do not change this file.
</auto-generated>
------------------------------------------------------------------------------
"""
import json
import sys
import re
from six import string_types
from .Package import Package
from .PackageVersion import PackageVersion
from .PaginationInfo import PaginationInfo
from .RequestStatus import RequestStatus

# Unused import over optimization prevention
str(repr(RequestStatus))
str(repr(PackageVersion))
str(repr(PaginationInfo))
str(repr(Package))


if sys.version_info > (3,):
    long = int
    unicode = str

class PackageVersionListResponse(object):
    """Response to fetching package version list"""
    def __init__(self, propDict=None):
        fromDict = propDict is not None and isinstance(propDict, dict)
        self.packageVersions = (
            None if not fromDict or propDict.get(
                "packageVersions"
            ) is None
            else [ PackageVersion(i)
            for i in propDict["packageVersions"] ])
        self.paginationInfo = (
            None if not fromDict or propDict.get(
                "paginationInfo"
            ) is None
            else propDict["paginationInfo"])
        self.pkg = (
            None if not fromDict or propDict.get(
                "pkg"
            ) is None
            else propDict["pkg"])
        self.requestStatus = (
            None if not fromDict or propDict.get(
                "requestStatus"
            ) is None
            else propDict["requestStatus"])

    @property
    def packageVersions(self):
        """ """
        return self._packageVersions

    @packageVersions.setter
    def packageVersions(self, value):
        if value is not None and not isinstance(value, list):
            value = list(value)
        if (value is None) or isinstance(value, list):
            self._packageVersions = value
        else:
            raise TypeError(
                'Property "packageVersions" of type "list<PackageVersion>" se'
                't to wrong type'
            )

    @property
    def paginationInfo(self):
        """PaginationInfo: Pagination Information"""
        return self._paginationInfo

    @paginationInfo.setter
    def paginationInfo(self, value):
        if value is not None and not isinstance(value, PaginationInfo):
            value = PaginationInfo(value)
        if (value is None) or isinstance(value, PaginationInfo):
            self._paginationInfo = value
        else:
            raise TypeError(
                'Property "paginationInfo" of type "list<PaginationInfo>" set'
                ' to wrong type'
            )

    @property
    def pkg(self):
        """ """
        return self._pkg

    @pkg.setter
    def pkg(self, value):
        if value is not None and not isinstance(value, Package):
            value = Package(value)
        if (value is None) or isinstance(value, Package):
            self._pkg = value
        else:
            raise TypeError(
                'Property "pkg" of type "list<Package>" set to wrong type'
            )

    @property
    def requestStatus(self):
        """RequestStatus: Request status information"""
        return self._requestStatus

    @requestStatus.setter
    def requestStatus(self, value):
        if value is not None and not isinstance(value, RequestStatus):
            value = RequestStatus(value)
        if (value is None) or isinstance(value, RequestStatus):
            self._requestStatus = value
        else:
            raise TypeError(
                'Property "requestStatus" of type "list<RequestStatus>" set t'
                'o wrong type'
            )

    def toDict(self):
        result = {}
        if self._packageVersions:
            result["packageVersions"] = [
                i.toDict() for i in self._packageVersions 
            ] if self._packageVersions else []
        if self._paginationInfo:
            result["paginationInfo"] = \
                self._paginationInfo.toDict() if self._paginationInfo is not None else None
        if self._pkg:
            result["pkg"] = \
                self._pkg.toDict() if self._pkg is not None else None
        if self._requestStatus:
            result["requestStatus"] = \
                self._requestStatus.toDict() if self._requestStatus is not None else None
        return result

    def toJSON(self, pretty=False):
        if pretty:
            return json.dumps(self.toDict(), sort_keys=True, indent=4)
        else:
            return json.dumps(self.toDict(), sort_keys=True)

    def isValid(self):
        if (self._pkg is not None): self._pkg.isValid()
        if (self._packageVersions is not None):
            for obj in self._packageVersions:
                if (obj is not None): obj.isValid()
        if (self._paginationInfo is not None): self._paginationInfo.isValid()
        if (self._requestStatus is not None): self._requestStatus.isValid()
        return True
    

