
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-22T16:56:24+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "1996c5184a19340cbc9236bf3c842840710be7e9",
 "version": "0.32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
