import os
from pathlib import Path

SLEEP_TIME = 1

## SAAS
# WS_URL = "wss://app.prophecy.io/api/lineage/ws"
# PROPHECY_PAT = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxLUtqdEp1eVpMQmhPV3QwQmxrTWxVZkFWM0k1Q01sNmwwSmg5N1FSUUYwNlRWcVY5NEhqc05HSFRyZzl3b3dsZG1zNmdyaDV2SUJmTER6RldCSWFvODYzbXo1OGc5ZDhKV1ljdURnVXpDVis0R1wvSGtUUExFPSIsImlzcyI6ImFwcF9zYWFzIiwiZXhwIjoxNzQ1MDY3MzU1LCJpYXQiOjE3MzA4MTQ5NTUsImp0aSI6IjNiNmE0Y2NlNDEyYmY5NjFkY2RiZDMxOWM3MzdjOTJjMmIwNThmNzU1OGJhZGE2NzcxYThhM2ZmZmFmY2YwMjZkMjk2NmUxYzc3OTA4MjA0MmMwNzIwNmQ5OTdkOTJlZGYwZmM1ZmRhODUzMTNiNDU0NmIxNzc1MjllMjY4YmI3YzQ0MDNhYTRjM2FlNmY5NjM2YWJlMzk0ZjM5MzQzY2Y3NmUxNWQwYmVkNGFlYjBlYmJjMDVlODIxYjc4YzgzODhmOWU4MDBjZWQ3MGNhZmI5MjRmZmE3ZDZlM2QyY2U5YzRmMGY4OTdiZjNhNmYzYTA2ZTVhMjNiNDdmNTk5YmIifQ.Bq4F-_BuZdDtjCKXi28lSCy1T1w__3Vf_PyYr6Ll3V0"

# ## ASHISHK3S
# PROPHECY_PAT = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxLUNQaHpyVXE4WUp6XC9VN3RXQzBoVlhvYUwzUzhvMmtLZGFHYUlONWFGeDVWa1pBUEVQM0JabkFTaWJnUEo3WXhEbm9lQlRsakkycXJkUTR1cDNTRjJQOEpQN05VdWlrckVjVStiU2t2TlB5RlUzSHZuYVdjPSIsImlzcyI6ImNwX2RldiIsImV4cCI6MTc0NTY2MzQ0OSwiaWF0IjoxNzMxNDExMDQ5LCJqdGkiOiJhM2FhNTM3NzZiNTkwM2Q1ZmI5ZWE2OTBiYzJiZGY4NzE3NGYyN2JjZjBiYzliNmVmMTI5NzZjNzEzOTM4ZGRiMDNmNzg4NDhjZWVkZjM1ZDc4MzA1NDgyMDk5NTE5MmU4MGQzMGZmNGE4MDYxNjhlMmI1NDZmNjk5ODY3YTdjYmRhMWRhYTgxMzg3NDlmOTY3MTk1MmZmOGJjOGZiNTEwZjUxMzBhMmMxYzRiNWUyZWM2MTRiOTliZDY1NjBmY2U3MjM1OTJkZGE4Yzg3NjUyZTBmMDdjNTk1Y2E2OWM5MDMxYjkwMTJkZmJkN2YyNTc1MGU0OTA0ZGQ2NjY5MmIxIn0.QMwFEW15ZHxapFtj2LoGj0LThtApkvcVNEjmKKKLzc8"
# WS_URL = "wss://ashishk3s.dev.cloud.prophecy.io/api/lineage/ws"
# PROJECT_ID = "3"

# WEB SOCKET
# PROJECT_ID = "35835"
# PIPELINE_IDS = [
#     "TestCleansingGem"
#     ]

# PROJECT_ID = "6512"
# PIPELINE_IDS = [
#     "customer_orders",
#     # "GeneralTests",
#     # "OperatorsAndGems"
# ]


# ENV VARIABLES
PROPHECY_PAT = "PROPHECY_PAT"

PROPHECY_URL = "PROPHECY_URL"

PROJECT_ID = "PROJECT_ID"
PIPELINE_ID = "PIPELINE_ID"
SEND_EMAIL = "SEND_EMAIL"
