# coding: utf-8

"""
    VRt.Studio [ST]

    Veeroute Studio API.  # Description  Server part of the Veeroute Studio.  ## Entity relationship diagram  ![erd](../uml/studio.svg) 

    The version of the OpenAPI document: 7.11.2593
    Contact: servicedesk@veeroute.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TripStartTimeStrategy(str, Enum):
    """
    The strategy of the choosing optimal trip start time:   * `EARLIEST_FINISH`   * `LOWEST_COST` 
    """

    """
    allowed enum values
    """
    EARLIEST_FINISH = 'EARLIEST_FINISH'
    LOWEST_COST = 'LOWEST_COST'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TripStartTimeStrategy from a JSON string"""
        return cls(json.loads(json_str))


