# Generated by Django 3.2.6 on 2022-06-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerLock',
            fields=[
                ('lock_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('owner', models.CharField(max_length=512, unique=True)),
                ('valid_until', models.BigIntegerField()),
                ('fencing_token_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'aistudio_scheduler_lock',
            },
        ),
    ]
