# Generated by Django 5.0.1 on 2024-11-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcolourpicker', '0002_alter_color_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_name',
            field=models.CharField(help_text='The name of the color that will show up on the form.', max_length=255, null=True, unique=True),
        ),
    ]
