fun_facts = [
    "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still edible.",
    "Octopuses have three hearts and blue blood.",
    "A day on Venus is longer than a year on Venus. Venus takes 243 Earth days to rotate once but only 225 Earth days to orbit the Sun.",
    "Bananas are berries, but strawberries aren't.",
    "The Eiffel Tower can be 15 cm taller during the summer due to the expansion of iron in the heat.",
    "Wombat poop is cube-shaped, which helps it not to roll away.",
    "Sharks have been around longer than trees. They first appeared about 400 million years ago, while the earliest trees appeared around 350 million years ago.",
    "A group of flamingos is called a 'flamboyance.'",
    "The human nose can detect about 1 trillion different scents.",
    "A blue whale’s heart is as large as a small car and can weigh as much as 2,000 pounds.",
    "There are more trees on Earth than stars in the Milky Way galaxy. There are about 3 trillion trees and around 100-400 billion stars in the Milky Way.",
    "Kangaroos cannot walk backwards.",
    "Venus is the hottest planet in our solar system, with temperatures that can reach up to 900 degrees Fahrenheit (475 degrees Celsius).",
    "Humans and giraffes have the same number of neck vertebrae: seven.",
    "There are more possible iterations of a game of chess than there are atoms in the known universe.",
    "Sea otters hold hands when they sleep to keep from drifting apart.",
    "You can’t hum while holding your nose. Try it!",
    "There are 60,000 miles of blood vessels in the human body.",
    "A single strand of spaghetti is called a 'spaghetto.'",
    "Elephants are the only animals that can't jump.",
    "The longest word in the English language is 'pneumonoultramicroscopicsilicovolcanoconiosis,' a lung disease caused by inhaling fine silica dust.",
    "A snail can sleep for three years.",
    "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.",
    "A cow-bison hybrid is called a 'beefalo.'",
    "In Japan, it’s common to eat KFC for Christmas dinner.",
    "A group of crows is called a 'murder.'",
    "The inventor of the Pringles can is now buried in one.",
    "The longest time between two twins being born is 87 days.",
    "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid of Giza.",
    "An octopus has three hearts, nine brains, and blue blood.",
    "The largest living organism is a fungus in Oregon that covers over 2,385 acres.",
    "Polar bear skin is black, and their fur is transparent.",
    "The shortest complete sentence in the English language is 'I am.'",
    "A group of owls is called a 'parliament.'",
    "The human body contains around 37.2 trillion cells.",
    "The unicorn is Scotland's national animal.",
    "There are about 200,000 weather satellites orbiting Earth.",
    "The longest hiccuping spree lasted for 68 years.",
    "A cockroach can live several weeks without its head.",
    "Mice sing to each other, but humans cannot hear them.",
    "The world’s largest desert is Antarctica.",
    "The Eiffel Tower can grow more than 6 inches during the summer due to thermal expansion.",
    "The first email was sent by Ray Tomlinson to himself in 1971.",
    "A giraffe's neck contains the same number of vertebrae as a human's neck: seven.",
    "The longest recorded flight of a chicken is 13 seconds.",
    "It takes eight minutes and 20 seconds for light to travel from the Sun to the Earth.",
    "The smell of freshly cut grass is actually a plant distress call.",
    "There are more stars in the universe than grains of sand on all the world’s beaches.",
    "The world's largest grand piano was built by a 15-year-old in New Zealand.",
    "Tigers have striped skin, not just striped fur.",
    "A group of jellyfish is called a 'smack.'",
    "The human brain is about 75% water.",
    "A day on Mercury is 59 Earth days long.",
    "There are more bacteria in your mouth than there are people on Earth.",
    "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.",
    "An average person will spend six months of their life waiting for red lights to turn green.",
    "A giraffe's tongue can be up to 18 inches long.",
    "A honeybee can fly at speeds of up to 15 miles per hour.",
    "Humans share about 60% of their DNA with bananas.",
    "A group of pandas is called an 'embarrassment.'",
    "The heart of a shrimp is located in its head.",
    "Humans have been farming for around 12,000 years.",
    "The average person walks the equivalent of five times around the world in their lifetime.",
    "The world's smallest mammal is the bumblebee bat.",
    "Sharks have been around longer than trees. They first appeared about 400 million years ago.",
    "A newborn kangaroo is the size of a lima bean.",
    "It is impossible to hum while holding your nose.",
    "The shortest commercial flight in the world is between two Scottish islands, Westray and Papa Westray, and takes about 90 seconds.",
    "A chameleon's tongue is twice the length of its body.",
    "The world’s oldest piece of chewing gum is over 9,000 years old.",
    "The longest recorded flight of a chicken is 13 seconds.",
    "There are more possible iterations of a game of chess than there are atoms in the known universe.",
    "The name for the shape of Pringles is called a 'hyperbolic paraboloid.'",
    "A group of owls is called a 'parliament.'",
    "The world’s largest desert is Antarctica.",
    "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.",
    "It is impossible for most people to lick their own elbow.",
    "Elephants are the only animals that can’t jump.",
    "The longest time between two twins being born is 87 days.",
    "A group of flamingos is called a 'flamboyance.'",
    "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still edible.",
    "A day on Venus is longer than a year on Venus.",
    "Bananas are berries, but strawberries aren’t.",
    "Wombat poop is cube-shaped.",
    "The Eiffel Tower can be 15 cm taller during the summer.",
    "Sharks have been around longer than trees.",
    "A blue whale’s heart can weigh as much as 2,000 pounds.",
    "There are more trees on Earth than stars in the Milky Way galaxy.",
    "Kangaroos cannot walk backwards.",
    "Venus is the hottest planet in our solar system.",
    "Humans and giraffes have the same number of neck vertebrae.",
    "Sea otters hold hands when they sleep.",
    "You can’t hum while holding your nose.",
    "There are 60,000 miles of blood vessels in the human body.",
    "A single strand of spaghetti is called a 'spaghetto.'",
    "Elephants are the only animals that can't jump.",
    "The longest word in the English language is 'pneumonoultramicroscopicsilicovolcanoconiosis.'",
    "A snail can sleep for three years.",
    "The shortest war in history was between Britain and Zanzibar.",
    "A cow-bison hybrid is called a 'beefalo.'",
    "In Japan, it’s common to eat KFC for Christmas dinner.",
    "A group of crows is called a 'murder.'",
    "The inventor of the Pringles can is now buried in one.",
    "The longest time between two twins being born is 87 days.",
    "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid of Giza.",
    "An octopus has three hearts, nine brains, and blue blood.",
    "The largest living organism is a fungus in Oregon.",
    "Polar bear skin is black, and their fur is transparent.",
    "The shortest complete sentence in the English language is 'I am.'",
    "A group of owls is called a 'parliament.'",
    "The human body contains around 37.2 trillion cells.",
    "The unicorn is Scotland's national animal.",
    "There are about 200,000 weather satellites orbiting Earth.",
    "The longest hiccuping spree lasted for 68 years.",
    "A cockroach can live several weeks without its head.",
    "Mice sing to each other, but humans cannot hear them.",
    "The world’s largest desert is Antarctica.",
    "The Eiffel Tower can grow more than 6 inches during the summer.",
    "The first email was sent by Ray Tomlinson to himself in 1971.",
    "A giraffe's neck contains the same number of vertebrae as a human's neck: seven.",
    "The longest recorded flight of a chicken is 13 seconds.",
    "It takes eight minutes and 20 seconds for light to travel from the Sun to the Earth.",
    "The smell of freshly cut grass is actually a plant distress call.",
    "There are more stars in the universe than grains of sand on all the world’s beaches.",
    "The world's largest grand piano was built by a 15-year-old in New Zealand.",
    "Tigers have striped skin, not just striped fur.",
    "A group of jellyfish is called a 'smack.'",
    "The human brain is about 75% water.",
    "A day on Mercury is 59 Earth days long.",
    "There are more bacteria in your mouth than there are people on Earth.",
    "The shortest war in history was between Britain and Zanzibar.",
    "An average person will spend six months of their life waiting for red lights to turn green.",
    "A giraffe's tongue can be up to 18 inches long.",
    "A honeybee can fly at speeds of up to 15 miles per hour.",
    "Humans share about 60% of their DNA with bananas.",
    "A group of pandas is called an 'embarrassment.'",
    "The heart of a shrimp is located in its head.",
    "Humans have been farming for around 12,000 years.",
    "The average person walks the equivalent of five times around the world in their lifetime.",
    "The world's smallest mammal is the bumblebee bat.",
    "Sharks have been around longer than trees.",
    "A newborn kangaroo is the size of a lima bean.",
    "It is impossible to hum while holding your nose.",
    "The shortest commercial flight in the world is between two Scottish islands, Westray and Papa Westray.",
    "A chameleon's tongue is twice the length of its body.",
    "The world’s oldest piece of chewing gum is over 9,000 years old.",
    "The longest recorded flight of a chicken is 13 seconds.",
    "There are more possible iterations of a game of chess than there are atoms in the known universe.",
    "The name for the shape of Pringles is called a 'hyperbolic paraboloid.'",
    "A group of owls is called a 'parliament.'",
    "The world’s largest desert is Antarctica.",
    "The shortest war in history was between Britain and Zanzibar.",
    "It is impossible for most people to lick their own elbow.",
    "Elephants are the only animals that can’t jump.",
    "The longest time between two twins being born is 87 days.",
    "A group of flamingos is called a 'flamboyance.'",
    "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still edible.",
    "A day on Venus is longer than a year on Venus.",
    "Bananas are berries, but strawberries aren’t.",
    "Wombat poop is cube-shaped.",
    "The Eiffel Tower can be 15 cm taller during the summer.",
    "Sharks have been around longer than trees.",
    "A blue whale’s heart can weigh as much as 2,000 pounds.",
    "There are more trees on Earth than stars in the Milky Way galaxy.",
    "Kangaroos cannot walk backwards.",
    "Venus is the hottest planet in our solar system.",
    "Humans and giraffes have the same number of neck vertebrae.",
    "Sea otters hold hands when they sleep.",
    "You can’t hum while holding your nose.",
    "There are 60,000 miles of blood vessels in the human body.",
    "A single strand of spaghetti is called a 'spaghetto.'",
    "Elephants are the only animals that can't jump.",
    "The longest word in the English language is 'pneumonoultramicroscopicsilicovolcanoconiosis.'",
    "A snail can sleep for three years.",
    "The shortest war in history was between Britain and Zanzibar.",
    "A cow-bison hybrid is called a 'beefalo.'",
    "In Japan, it’s common to eat KFC for Christmas dinner.",
    "A group of crows is called a 'murder.'",
    "The inventor of the Pringles can is now buried in one.",
    "The longest time between two twins being born is 87 days.",
    "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid of Giza.",
    "An octopus has three hearts, nine brains, and blue blood.",
    "The largest living organism is a fungus in Oregon.",
    "Polar bear skin is black, and their fur is transparent.",
    "The shortest complete sentence in the English language is 'I am.'",
    "A group of owls is called a 'parliament.'",
    "The human body contains around 37.2 trillion cells.",
    "The unicorn is Scotland's national animal.",
    "There are about 200,000 weather satellites orbiting Earth.",
    "The longest hiccuping spree lasted for 68 years.",
    "A cockroach can live several weeks without its head.",
    "Mice sing to each other, but humans cannot hear them.",
    "The world’s largest desert is Antarctica.",
    "The Eiffel Tower can grow more than 6 inches during the summer.",
    "The first email was sent by Ray Tomlinson to himself in 1971.",
    "A giraffe's neck contains the same number of vertebrae as a human's neck: seven.",
    "The longest recorded flight of a chicken is 13 seconds.",
    "It takes eight minutes and 20 seconds for light to travel from the Sun to the Earth.",
    "The smell of freshly cut grass is actually a plant distress call.",
    "There are more stars in the universe than grains of sand on all the world’s beaches.",
    "The world's largest grand piano was built by a 15-year-old in New Zealand.",
    "Tigers have striped skin, not just striped fur.",
    "A group of jellyfish is called a 'smack.'",
    "The human brain is about 75% water.",
    "A day on Mercury is 59 Earth days long.",
    "There are more bacteria in your mouth than there are people on Earth.",
    "The shortest war in history was between Britain and Zanzibar.",
    "An average person will spend six months of their life waiting for red lights to turn green.",
    "A giraffe's tongue can be up to 18 inches long.",
    "A honeybee can fly at speeds of up to 15 miles per hour.",
    "Humans share about 60% of their DNA with bananas.",
    "A group of pandas is called an 'embarrassment.'",
    "The heart of a shrimp is located in its head.",
    "Humans have been farming for around 12,000 years.",
    "The average person walks the equivalent of five times around the world in their lifetime.",
    "The world's smallest mammal is the bumblebee bat.",
    "Sharks have been around longer than trees.",
    "A newborn kangaroo is the size of a lima bean.",
    "It is impossible to hum while holding your nose.",
    "The shortest commercial flight in the world is between two Scottish islands, Westray and Papa Westray.",
    "A chameleon's tongue is twice the length of its body.",
    "The world’s oldest piece of chewing gum is over 9,000 years old.",
    "The longest recorded flight of a chicken is 13 seconds.",
    "There are more possible iterations of a game of chess than there are atoms in the known universe.",
    "The name for the shape of Pringles is called a 'hyperbolic paraboloid.'",
    "A group of owls is called a 'parliament.'",
    "The world’s largest desert is Antarctica.",
    "The shortest war in history was between Britain and Zanzibar.",
    "It is impossible for most people to lick their own elbow.",
    "Elephants are the only animals that can’t jump.",
    "The longest time between two twins being born is 87 days.",
    "A group of flamingos is called a 'flamboyance.'",
    "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still edible.",
    "A day on Venus is longer than a year on Venus.",
    "Bananas are berries, but strawberries aren’t.",
    "Wombat poop is cube-shaped.",
    "The Eiffel Tower can be 15 cm taller during the summer.",
    "Sharks have been around longer than trees.",
    "A blue whale’s heart can weigh as much as 2,000 pounds.",
    "There are more trees on Earth than stars in the Milky Way galaxy.",
    "Kangaroos cannot walk backwards.",
    "Venus is the hottest planet in our solar system.",
    "Humans and giraffes have the same number of neck vertebrae.",
    "Sea otters hold hands when they sleep.",
    "You can’t hum while holding your nose.",
    "There are 60,000 miles of blood vessels in the human body.",
    "A single strand of spaghetti is called a 'spaghetto.'",
    "Elephants are the only animals that can't jump.",
    "The longest word in the English language is 'pneumonoultramicroscopicsilicovolcanoconiosis.'",
    "A snail can sleep for three years.",
    "The shortest war in history was between Britain and Zanzibar.",
    "A cow-bison hybrid is called a 'beefalo.'",
    "In Japan, it’s common to eat KFC for Christmas dinner.",
    "A group of crows is called a 'murder.'",
    "The inventor of the Pringles can is now buried in one.",
    "The longest time between two twins being born is 87 days.",
    "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid of Giza.",
    "An octopus has three hearts, nine brains, and blue blood.",
    "The largest living organism is a fungus in Oregon.",
    "Polar bear skin is black, and their fur is transparent.",
    "The shortest complete sentence in the English language is 'I am.'",
    "A group of owls is called a 'parliament.'",
    "The human body contains around 37.2 trillion cells.",
    "The unicorn is Scotland's national animal.",
    "There are about 200,000 weather satellites orbiting Earth.",
    "The longest hiccuping spree lasted for 68 years.",
    "A cockroach can live several weeks without its head.",
    "Mice sing to each other, but humans cannot hear them.",
    "The world’s largest desert is Antarctica.",
    "The Eiffel Tower can grow more than 6 inches during the summer.",
    "The first email was sent by Ray Tomlinson to himself in 1971.",
    "A giraffe's neck contains the same number of vertebrae as a human's neck: seven.",
    "The longest recorded flight of a chicken is 13 seconds.",
    "It takes eight minutes and 20 seconds for light to travel from the Sun to the Earth.",
    "The smell of freshly cut grass is actually a plant distress call.",
    "There are more stars in the universe than grains of sand on all the world’s beaches.",
    "The world's largest grand piano was built by a 15-year-old in New Zealand.",
    "Tigers have striped skin, not just striped fur.",
    "A group of jellyfish is called a 'smack.'",
    "The human brain is about 75% water.",
    "A day on Mercury is 59 Earth days long.",
    "There are more bacteria in your mouth than there are people on Earth.",
    "The shortest war in history was between Britain and Zanzibar.",
    "An average person will spend six months of their life waiting for red lights to turn green.",
    "A giraffe's tongue can be up to 18 inches long.",
    "A honeybee can fly at speeds of up to 15 miles per hour.",
    "Humans share about 60% of their DNA with bananas.",
    "A group of pandas is called an 'embarrassment.'",
    "The heart of a shrimp is located in its head.",
    "Humans have been farming for around 12,000 years.",
    "The average person walks the equivalent of five times around the world in their lifetime.",
    "The world's smallest mammal is the bumblebee bat.",
    "Sharks have been around longer than trees.",
    "A newborn kangaroo is the size of a lima bean.",
    "It is impossible to hum while holding your nose.",
    "The shortest commercial flight in the world is between two Scottish islands, Westray and Papa Westray.",
    "A chameleon's tongue is twice the length of its body.",
    "The world’s oldest piece of chewing gum is over 9,000 years old.",
    "The longest recorded flight of a chicken is 13 seconds.",
    "There are more possible iterations of a game of chess than there are atoms in the known universe.",
    "The name for the shape of Pringles is called a 'hyperbolic paraboloid.'",
    "A group of owls is called a 'parliament.'",
    "The world’s largest desert is Antarctica.",
    "The shortest war in history was between Britain and Zanzibar.",
    "It is impossible for most people to lick their own elbow.",
    "Elephants are the only animals that can’t jump.",
    "The longest time between two twins being born is 87 days.",
    "A group of flamingos is called a 'flamboyance.'"
]
