
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-21T11:44:23+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0d77ced1a78e341a90e4eb807b47948f720d1824",
 "version": "2.9.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
