import omp4py.directives.clauses.collapse
import omp4py.directives.clauses.copyin
import omp4py.directives.clauses.copyprivate
import omp4py.directives.clauses.default
import omp4py.directives.clauses.firstprivate
import omp4py.directives.clauses.if_
import omp4py.directives.clauses.lastprivate
import omp4py.directives.clauses.nowait
import omp4py.directives.clauses.num_threads
import omp4py.directives.clauses.ordered
import omp4py.directives.clauses.private
import omp4py.directives.clauses.reduction
import omp4py.directives.clauses.schedule
import omp4py.directives.clauses.shared
import omp4py.directives.clauses.untied