# Generated by Django 4.1.2 on 2022-11-21 00:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("intecomm_rando", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalregisteredgroup",
            name="group_identifier",
            field=models.CharField(
                db_index=True, help_text="Updated when group is randomized", max_length=36
            ),
        ),
        migrations.AlterField(
            model_name="historicalregisteredgroup",
            name="group_identifier_as_pk",
            field=models.UUIDField(
                db_index=True,
                help_text="Set to same value from PatientGroup when group is registered",
            ),
        ),
        migrations.AlterField(
            model_name="historicalregisteredgroup",
            name="randomization_datetime",
            field=models.DateTimeField(
                blank=True, help_text="Updated when group is randomized", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalregisteredgroup",
            name="randomization_list_model",
            field=models.CharField(
                help_text="Updated when group is randomized", max_length=150, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalregisteredgroup",
            name="sid",
            field=models.CharField(
                db_index=True,
                default=uuid.uuid4,
                help_text="Default value is UUID for unique constraint. Updated to a real SID when group is randomized",
                max_length=36,
                verbose_name="SID",
            ),
        ),
        migrations.AlterField(
            model_name="registeredgroup",
            name="group_identifier",
            field=models.CharField(
                help_text="Updated when group is randomized", max_length=36, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="registeredgroup",
            name="group_identifier_as_pk",
            field=models.UUIDField(
                help_text="Set to same value from PatientGroup when group is registered",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="registeredgroup",
            name="randomization_datetime",
            field=models.DateTimeField(
                blank=True, help_text="Updated when group is randomized", null=True
            ),
        ),
        migrations.AlterField(
            model_name="registeredgroup",
            name="randomization_list_model",
            field=models.CharField(
                help_text="Updated when group is randomized", max_length=150, null=True
            ),
        ),
        migrations.AlterField(
            model_name="registeredgroup",
            name="sid",
            field=models.CharField(
                default=uuid.uuid4,
                help_text="Default value is UUID for unique constraint. Updated to a real SID when group is randomized",
                max_length=36,
                unique=True,
                verbose_name="SID",
            ),
        ),
    ]
