#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2405-50-g22797971"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2405
#define NETGEN_VERSION_TWEAK 50
#define NETGEN_VERSION_HASH "g22797971"
#endif // NETGEN_VERSION_HPP_INCLUDED
